package com.company;

public enum TipoMoneda {
    DOLAR_CANADIENSE, DOLAR_HONGKONES, CORONA_ISLANDESA,
    PESO_FILIPINO, CORONA_DANESA, FORINTO_HUNGARO,
    CORONA_CHECA, DOLAR_AUSTRIACO, DOLAR,
    LIBRA, EURO;
}