package com.company;

public enum TipoMoneda {
    YEN, DOLAR, LIBRA, EURO, DOLAR_CANADIENSE, DOLAR_HONGKONES, CORONA_ISLANDESA,
    PESO_FILIPINO, CORONA_DANESA, FORINTO_HUNGARO, CHELIN_AUSTRIACO, LEU, CORONA_SUECA,
    RUPIA_INDONESIA, RUPIA_INDIA, REAL_BRASILENO, RUBLO, KUNA, BAT, FRANCO_SUIZO,
    DOLAR_SINGAPURENSE, ESLOTI, LEV, LIRA_TURCA, YUAN, CORONA_NORUEGA, DOLAR_NEOZELANDES,
    RAND, PESO_MEXICANO, SEQUEL, WON, RINGIT, CORONA_CHECA
}